### ISSUE TITLE
Нужна подсветка для формата EDT

### ISSUE THREAD

**Issue by Oxotka** [ILazutin/1c-syntax-for-fecru#2]
Нужна подсветка для формата EDT

**Comment by ILazutin** [comment]
Для формата EDT подсветка тоже работает. Файлы модулей в EDT ничем не отличаются от модулей, выгруженных из конфигуратора, а файлы с расширением ".mdo" (описание объекта метаданных) подсвечиваются как "xml"-файлы
![2018-05-17_09h14_15](https://user-images.githubusercontent.com/24310716/40159723-3a9ab894-59b3-11e8-8f87-21a10b9198f1.png)
![2018-05-17_09h17_12](https://user-images.githubusercontent.com/24310716/40159725-3ab4f8b2-59b3-11e8-8b0f-bc3eaa44add3.png)

P.S. увидел, что не учел несколько EDT-шных расширений файлов (.cmi .cai .hpwa) - дополню filemap.

**Comment by ILazutin** [comment]
Добавил расширения файлов для формата 1С-EDT
см. https://github.com/ILazutin/1c-syntax-for-fecru/commit/f8337818790816afd62d2c1ee217da21a5b031c7
